---
title: "reading_from_web"
output: github_document
date: "2022-10-15"
---

```{r}
library(tidyverse)
library(rvest)
library(httr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)

drug_use_html
```

```{r}
drug_use_html %>%
  html_table() %>% #gets all the html table as lists
  first() %>% #only get first list
  slice(-1) #remove first row
```


## SW data

```{r}
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")
```


How do I get the stuff i want? CSS selector

```{r}
sw_titles = 
  swm_html %>%
  html_elements(".lister-item-header a") %>% #get CSS selector using SelectorGadget
  html_text()
```

```{r}
sw_runtime = 
  swm_html %>%
  html_elements(".runtime") %>%
  html_text()
```

```{r}
sw_money = 
  swm_html %>%
  html_elements(".text-small:nth-child(7) span:nth-child(5)") %>%
  html_text()
```

```{r}
sw_df = 
  tibble(
    title = sw_titles,
    runtime = sw_runtime,
    money = sw_money
  )
```


Let me just show Napoleon Dynamite...

## APIs

```{r}
water_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>%
  content("parsed") #clean df
```

```{r}
brfss_df = 
  GET(
    "https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
    query = list("$limit" = 5000)) %>% #get 5000 rows instead of default 1000 rows
  content("parsed")
```

```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

names(poke)
poke[["weight"]]
```

