---
title: "strings_and_factors"
output: github_document
date: "2022-10-23"
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(p8105.datasets)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## String Vectors

```{r}
string_vec = c("my", "name", "is", "jeff")

str_detect(string_vec, "jeff")
str_replace(string_vec, "jeff", "Jeff")
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think")
str_detect(string_vec, "^i think") #starts with i think
str_detect(string_vec, "i think$") #ends with i think
```


```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"[Bb]ush") #either upper or lower case b
str_detect(string_vec,"[Bb][Uu][Ss][Hh]")
```


```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]") #any number followed by a either lower or upper letter
```


```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11") #anything between 7 and 11, but not 711
```


```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[") #find [, need \\ because [ is a regex
str_detect(string_vec, "\\[[0-9]") #find [ followed by num
```


## Why factors are weird

```{r}
vec_sex = factor(c("male", "male", "female", "female"))
vec_sex #automatically in alphabetical factor level
```

```{r}
vec_sex = fct_relevel(vec_sex, "male") #make male the first factor level
vec_sex
```


## NSDUH
```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

table_marj = 
  read_html(nsduh_url) %>% 
  html_table() %>% 
  first() %>%
  slice(-1)
```

tidy up the NSDUH data

```{r}
marj_df = 
  table_marj %>%
  select(-contains("P value")) %>%
  pivot_longer(
    -State, #pivot anything except for state
    names_to = "age_year",
    values_to = "percent"
  ) %>%
  mutate(
    percent = str_replace(percent, "[a-b]$", ""), #get rid of a,b,c at the end
    percent = as.numeric(percent)
  ) %>%
  separate(age_year, into = c("age", "year"), sep = "\\(") %>% #( is a regex, use \\( to separate at (
  mutate(
    year = str_replace(year, "\\)", "")
  ) %>%
  filter(
    !(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West", "District of Columbia")) #get rid of rows where state are these
  )
```


```{r}
marj_df %>%
  filter(age == "12-17") %>%
  mutate(State = fct_reorder(State, percent)) %>%
  ggplot(aes(x = State, y =percent, color = year)) +
  geom_point() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```


## Restaurant inspections

```{r}
data("rest_inspec")

rest_inspec %>%
  group_by(boro, grade) %>%
  summarize(n_obs = n()) %>%
  pivot_wider(
    names_from = grade,
    values_from = n_obs
  )
```

```{r}
rest_inspec = 
  rest_inspec %>%
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>%
  mutate(boro = str_to_title(boro)) #Captialize first letter

rest_inspec %>%
  group_by(boro, grade) %>%
  summarize(n_obs = n()) %>%
  pivot_wider(
    names_from = grade,
    values_from = n_obs
  )
```


Let's find pizza places

```{r}
rest_inspec %>%
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>%
  group_by(boro) %>%
  summarize(n_pizza = n())
```

```{r}
rest_inspec %>%
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>%
  mutate(boro = fct_infreq(boro)) %>% #factor in order of frequency of dba
  ggplot(aes(x = boro)) +
  geom_bar()
```


```{r}
rest_inspec %>%
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>%
  mutate(
    boro = fct_infreq(boro),
    boro = fct_recode(boro, "The City" = "Manhattan") #rename factor variable
    ) %>% #factor in order of frequency of dba
  ggplot(aes(x = boro)) +
  geom_bar()
```
